# Generated by Django 2.2.4 on 2022-09-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20220904_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
